version: '3'
services:
  mariadb:
    image: mysql:5.7.23 #no era maria ???
    volumes:
      - ./db:/var/lib/mysql    
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - BackEnd

  glpi:
    depends_on:
      - mariadb        
    image: diouxx/glpi
    expose:
      - "80"    
    restart: unless-stopped
    volumes:
      - ./files:/var/www/html/files
      - ./glpi:/var/www/html/glpi
      - ./plugins:/var/www/html/glpi/plugins
    environment:
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       VIRTUAL_HOST: ${VIRTUAL_HOST}
       LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    networks:
      - Default
      - BackEnd

networks:
  Default:
    external: 
        name: webproxy
  BackEnd:
    driver: bridge
